name: CI

on:
  push:
    branches: [develop]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (APT, no MPI, pre-built ESMF)
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get install -y libnetcdf-dev libnetcdff-dev
          liblapack-dev libopenblas-dev

      - name: Fetch pre-built ESMF
        run: |
          v="8.3.1"  # ESMF
          gcc="12"
          esmf_base=$HOME/esmf
          esmf=${v}-gcc-${gcc}-mpiuni

          export ESMF_DIR=${esmf_base}/${esmf}
          mkdir -p $ESMF_DIR
          cd $ESMF_DIR
          wget https://github.com/zmoon/gha-esmf/releases/download/v0.0.5/${esmf}.tar.gz
          tar xzvf ${esmf}.tar.gz

          echo "ESMFMKFILE=${ESMF_DIR}/lib/libO/Linux.gfortran.64.mpiuni.default/esmf.mk" >> "$GITHUB_ENV"

      - name: Configure
        run: FC=gfortran-12 cmake -S . -B build

      - name: Build
        run: cmake --build build
