name: GCC Linux Build and Test
on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container:
      image: jcsda/docker-gnu-openmpi-dev:skylab-v8

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: build
        run: |
          export CC=mpicc
          export FC=mpif90
          mkdir -p build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=../install ..
          make -j2 VERBOSE=1
          make install

      - name: test
        run: |
          set -x
          bin="$PWD/build/bin/nexus"
          failed=0
          cd tests/cases
          for d in *; do
            [ -d "$d" ] || continue
            cd $d
            $bin -c NEXUS_Config.rc -r grid_spec.nc || failed=1
            if [[ "$failed" == 1 ]]; then
              [ -f NEXUS.log ] && tail -n 20 NEXUS.log
              [ -f PET0.ESMF_LogFile ] && cat PET0.ESMF_LogFile
              exit 1
            fi
            cd ..
          done
